roles:
  default: "assistant.yaml"
  developer: "dev_assistant.yaml"
  file_update_recognize: "file_update_recognizer.yaml"
  cyber_friend: "cyber_friend.yaml"
  booster: "booster.yaml" # not released yet. Require strong reasoning model like deepseek-r1